# Generated by Django 3.1.3 on 2021-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=254)),
                ('estado', models.CharField(max_length=200)),
                ('celular', models.IntegerField()),
                ('observacoes', models.TextField(max_length=5000)),
            ],
        ),
    ]
