# Generated by Django 3.1.3 on 2021-02-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Agendar',
        ),
    ]
