# Generated by Django 3.1.3 on 2021-02-04 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dna_app', '0002_auto_20210202_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendar',
            name='observacoes',
            field=models.TextField(max_length=500),
        ),
    ]
